### ISSUE TITLE
Bug: Search Input Not Working by Address

### ISSUE THREAD

**Issue by rareweasel** [yearn/yearn-watch#106]
If I copy a strategy address from a random vault and paste it into the input search, it returns 0 strategies found.

Example: StrategyCurveEURT

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/89795397/183960315-32594fd9-68ae-4682-a825-72a697353fa5.png">
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/89795397/183960386-07b2d14c-9bfc-4501-ae46-b7d6530809dc.png">

**Comment by 0xMirim** [comment]
Hello, I took a look at this, and even thought it now appears to be resolved. I was seeing the same issue as you at the time and trying to isolate a cause. I was only having issues when searching for vaults on Ethereum, when doing the same search you described (CurveEURT). Other searches after I switched to Arbitrum and Fantom worked as expected both locally and on the production site. 

I did notice at the time I was getting 500 server errors on the main vaults page for the GET request  to http://localhost:3000/api/getVaults?chainID=1&revalidate=false 

This combined with the fact that it is now resolved makes me think it wasn't an issue with the actual yearn watch site but instead an issue with the API / data source.

**Comment by 0xMirim** [comment]
Not sure it's related to this specific issue but I will note that I still see errors in the terminal on the main vaults page when running in dev mode. Stuff like:

 requestMethod="POST", url="https://rpc.flashbots.net", code=SERVER_ERROR, version=web/5.6.1)  
...
  reason: 'processing response error',
    code: 'SERVER_ERROR',
    body: '{"id":47,"error":{"code":-32011,"message":"no backends available for method"},"jsonrpc":"2.0"}\n',
    error: Error: no backends available for method


Maybe worth seeing if you can re-create to see if you feel it's relevant? I'm no so familiar with the repo yet so it's hard for me to tell.

**Comment by rareweasel** [comment]
Hey @0xMirim thank you very much for the details. I will share this with the API team just in case.

**Comment by Majorfi** [comment]
Hey @rareweasel 
FYI, search by strategies have a special "pattern"
You should search one of:
- `strat: 0x26AB2029083909FeEFF8Cb0fA04c1CfF52499DE7`
- `strats: 0x26AB2029083909FeEFF8Cb0fA04c1CfF52499DE7`
- `strategy: 0x26AB2029083909FeEFF8Cb0fA04c1CfF52499DE7`
- `strategies: 0x26AB2029083909FeEFF8Cb0fA04c1CfF52499DE7`

The `strat[*]:` indicator enable the search by strategies
Just to be sure, test it on the `next` branch: https://next.yearn.watch/
