### ISSUE TITLE
FRP: On `track Keep CRV` page make all columns sort-able

### ISSUE THREAD

**Issue by DarkGhost7** [yearn/yearn-watch#115]
### What is your proposal 🚀
Make all columns sort-able not just the first and second one. This is so you can easily see which has the highest keepcrv %

![image](https://user-images.githubusercontent.com/38810205/185964528-6c609aa9-7d81-4b23-95ef-a50e511cf257.png)

### What does this solve ? 🛠
Easier to see the data

### More 🔎
*N/A*

**Comment by CutupAngel** [comment]
I will handle this one.
I already worked on track page.
@Majorfi  @magic990619  @DarkGhost7

**Comment by CutupAngel** [comment]
I finished this one.
Please check my [PR](https://github.com/yearn/yearn-watch/pull/126) for this.
@Majorfi @DarkGhost7
