### ISSUE TITLE
Bug: Subgraph link wrong

### ISSUE THREAD

**Issue by DarkGhost7** [yearn/yearn-watch#116]
### What happened 🆘
![image](https://user-images.githubusercontent.com/38810205/185965183-351754cf-f549-4220-b9a6-3e87cfd726c6.png)
The Subgraph link should point to the currently selected network's active subgraph or the github repo we use to track it. It is pointing to gov.yearn.finance atm. 

### To Reproduce 🔂
Steps to reproduce the behavior: hover over subgraph at the bottom.

**Comment by karelianpie** [comment]
@DarkGhost7, do you happen to know what are the endpoints for each chain?

I've got the draft PR https://github.com/yearn/yearn-watch/pull/119 ready just needing the actual endpoints

**Comment by DarkGhost7** [comment]
@karelianpie I will look into it and get them for you

**Comment by DarkGhost7** [comment]
@Majorfi when you're free

**Comment by Majorfi** [comment]
I need confirmation for Fantom, but here are the one used by yDaemon:
case 1: `https://api.thegraph.com/subgraphs/name/rareweasel/yearn-vaults-v2-subgraph-mainnet`
case 10: `https://api.thegraph.com/subgraphs/name/yearn/yearn-vaults-v2-optimism`
case 250: `https://api.thegraph.com/subgraphs/name/bsamuels453/yearn-fantom-validation-grafted`
case 42161: `https://api.thegraph.com/subgraphs/name/yearn/yearn-vaults-v2-arbitrum`

@karelianpie could you make them in a constant file or something? Will ask for confirmation!

**Comment by karelianpie** [comment]
> @karelianpie could you make them in a constant file or something? Will ask for confirmation!

I reckon we could just add them in the `StandardFooter.tsx`, i.e. https://github.com/yearn/yearn-watch/pull/119/commits/79f77e1cb0d5a7fcfa5a6ffc47a4734d5808c1ad -- if all good PR https://github.com/yearn/yearn-watch/pull/119 is ready for review

Or do you have a strong preference for adding these in a new file @Majorfi?
