### ISSUE TITLE
Bug: The strategies in the description seem to add yv to the token

### ISSUE THREAD

**Issue by DarkGhost7** [yearn/yearn-watch#118]
### What happened 🆘
Yearn watch is appending yv to the strategies deposit token when it should not. 

It should be looking for {{token}} from our ydeamon repo (https://github.com/yearn/ydaemon/blob/main/data/meta/strategies/1/ConvexReinvest.json#L4)

### To Reproduce 🔂
Steps to reproduce the behavior: go to yearn.watch or next.yearn.watch and look at any strategy even non-curve ones. 

### More 🔎
What it should look like (vaults.yearn.finance)
![image](https://user-images.githubusercontent.com/38810205/187239368-261b5f9b-ac7a-4242-bbaa-79ed47ad1f1d.png)
What I see
![image](https://user-images.githubusercontent.com/38810205/187239506-6b4618a8-73fc-4e23-89c2-e6020d7baf4c.png)

**Comment by Majorfi** [comment]
Pushed a fix to `next` branch, should be good in a few minutes!
Thank you for the report!

**Comment by DarkGhost7** [comment]
Thanks!

**Comment by DarkGhost7** [comment]
This is also happening on the strategy details pages 
![image](https://user-images.githubusercontent.com/38810205/199054014-8e931425-6df9-4b71-8a42-faf0135e8989.png)
https://yearn.watch/vault/0x490bD0886F221A5F79713D3E84404355A9293C50/0x000007252AB8d9120005d30aA15567Ea8de9a110

**Comment by ai-slave** [comment]
@DarkGhost7 how should it look like instead? Object has the name as "Curve ibCHF", is this right?

**Comment by DarkGhost7** [comment]
Yes this should not show yv-token just token, so yes just Curve-ibCHF @ai-slave
