### ISSUE TITLE
Bug: When a risk group name gets too long the formatting looks off 

### ISSUE THREAD

**Issue by DarkGhost7** [yearn/yearn-watch#123]
### What happened 🆘
![image](https://user-images.githubusercontent.com/38810205/190480033-d73ee2a9-2fee-4c51-9754-0c48b2c3508c.png)
The balancer risk group formatting seems off probably because it has a longer than normal name?

This happens even if the screen is fully expanded, I see alot of white space so maybe we can have a setting for expanding the website for bigger resolution screens. 

### To Reproduce 🔂
go to https://yearn.watch/risk and look for single sided balancer risk group. I have checked and it is correctly spaced in the https://github.com/yearn/ydaemon repo

**Comment by CutupAngel** [comment]
This is resolved on this [PR](https://github.com/yearn/yearn-watch/pull/127)

@DarkGhost7  @Majorfi
