### ISSUE TITLE
Bug: Possible typo?

### ISSUE THREAD

**Issue by DarkGhost7** [yearn/yearn-watch#124]
### What happened 🆘
![image](https://user-images.githubusercontent.com/38810205/190481667-4eb29faa-cfed-4a3c-b28a-1a2417def1d6.png)
Is this supposed to say debt? or is it like deposits?

### To Reproduce 🔂
Steps to reproduce the behavior: got to any strategies report page https://yearn.watch/vault/0xdb25cA703181E7484a155DD612b06f57E12Be5F0/0xDfFe2E8B9DD8Cc0367AAED727c07a8d2bB36Ed8b

**Comment by Majorfi** [comment]
Debt it is, indeed!
Fixed, thank you for the report!
