### ISSUE TITLE
FRP: Add custom node/rpc/endpoint selection as a backup

### ISSUE THREAD

**Issue by DarkGhost7** [yearn/yearn-watch#132]
**What is your proposal :rocket:** 
Add Custom endpoint selections in settings so you can locally override them in case one of them goes down.
This would default to the normal rpcs but let you override them with your own.

node rpc endpoints
subgraph endpoints
api/ydaemon endpoints

**What does this solve ? :hammer_and_wrench:** 
This lets anyone anywhere run this locally via their own nodes and subgraphs useful for testing

**Comment by Majorfi** [comment]
See #133
