### ISSUE TITLE
FRP: Integrate the template settings page

### ISSUE THREAD

**Issue by Majorfi** [yearn/yearn-watch#133]
### What is your proposal 🚀
We need to add a settings page (like web.ycorpo.com/settings), the one available in the template repo, to be able to overwrite some stuff, and mostly yDaemon Uri in case something is down!

The [`useSettings.tsx`](https://github.com/yearn/web-lib/blob/main/packages/web-lib/contexts/useSettings.tsx) exposes a bunch of functions to be able to overwrite the defaults settings used by the app.
Every app should use `useSettings` variables instead of local constants, variables or env.

For ex, the [`YDAEMON_BASE_URL`](https://github.com/yearn/yearn-watch/blob/main/next.config.js#L47) env variable should ne be used, but the [`yDaemonBaseURI`](https://github.com/yearn/web-lib/blob/4638bbd2a555059c74af9d23aafeeb6b7e5d31f7/packages/web-lib/contexts/useSettings.tsx#L11) should be used instead

### What does this solve ? 🛠
Provide a better **DE**fi and way to overwrite settings if our stuff are down

### More 🔎
Linked to #132

**Comment by ai-slave** [comment]
I can take this since it's almost the same as https://github.com/yearn/ySync/issues/81
