### ISSUE TITLE
FRP: [Allocations] clickable strategies

### ISSUE THREAD

**Issue by storming0x** [yearn/yearn-watch#135]
### What is your proposal 🚀
Allocations page shows detail list of strategies that use each particular protocol, would be good to add the feature to click and navigate through to the strategy detail page, to load vault info and other relevant information

### What does this solve ? 🛠
Analysis of allocations can pin point clearly which strategy on which vault is the one mentioned on the break down of allocation.

### More 🔎
*N/A*

![Screen Shot 2022-11-22 at 08 51 29](https://user-images.githubusercontent.com/6074987/203366148-949865bb-b844-4896-879a-ef107c6d79a0.png)

**Comment by MarcoWorms** [comment]
IDK if it fits this issue, would also be nice to link to the risk page for that strategy to see scores, today I have to open all accordeons on risk page and CTR+F the strategy name to be able to find it

**Comment by karelianpie** [comment]
Opened a PR for the main issue; https://github.com/yearn/yearn-watch/pull/139

> IDK if it fits this issue, would also be nice to link to the risk page for that strategy to see scores, today I have to open all accordeons on risk page and CTR+F the strategy name to be able to find it

@MarcoWorms That's a slightly different issue, as we don't have the ability to deep link to the strategies within a group. I'm wondering if a search bar in that table would help, or an expand all button? Also, could you please open an new issue to continue discussion? @Majorfi do you have an idea what could be best?
