### ISSUE TITLE
Bug: st-ycrv strategy isnt showing since it doesnt take on tvl (debt)

### ISSUE THREAD

**Issue by DarkGhost7** [yearn/yearn-watch#145]
### What happened 🆘
**A clear and concise description of what the bug is.**
Nothing is displayed when you go to this vault but the strategy is earning yield just not by putting funds to use in the traditional strategy way. This is a unique vault.
![image](https://user-images.githubusercontent.com/38810205/224352167-e0c16dbe-59f0-421f-ba59-39045e77cc81.png)

### To Reproduce 🔂
go here see no strategy https://yearn.watch/vault/0x27B5739e22ad9033bcBf192059122d163b60349D
maybe sort this specific strategy name by field "inQueue"=true
https://github.com/yearn/ydaemon/blob/develop/data/meta/strategies/1/CurveDaoFeeClaimBribesReinvest.json

**Comment by karelianpie** [comment]
There might be work to do here, but at the moment we're not getting the strategy from yDaemon, https://ydaemon.yearn.finance/1/vaults/all?strategiesDetails=withDetails

@Majorfi https://github.com/yearn/ydaemon/issues/225
