### ISSUE TITLE
Add support to detect keepCRV field

### ISSUE THREAD

**Issue by magic990619** [yearn/yearn-watch#20]
Some contract have keepCRV setting that we want to track and monitor, this is another field that is not generic so we need a similar approach to https://github.com/yearn/yearn-watch-legacy/issues/74 for this field.

Ideally the implementation can pave the road to making it easy to add new fields as we need to monitor, in this case it may be solved by checking a regex or CRV string in strategy name to detect that is most likely to have the field

https://github.com/yearn/yearn-watch-legacy/issues/75
https://github.com/yearn/yearn-watch-legacy/pull/331

**Comment by CutupAngel** [comment]
I will handle this issue. @magic990619
