### ISSUE TITLE
Redirect link to Transaction link on strategy reports

### ISSUE THREAD

**Issue by magikadev** [yearn/yearn-watch#50]
![image_2022-06-14_11-21-16](https://user-images.githubusercontent.com/46446076/173529012-bd884376-0d55-4af7-b95c-9be47433d6f0.png)

the link shoud use tx instead of address in etherscan

**Comment by magikadev** [comment]
This bug is because of `TxHashWithActions` component from web-lib.

https://github.com/yearn/web-lib/blob/1196865c9d9752672ff1e4e85b7b232e1d62fd70/packages/web-lib/components/TxHashWithActions.tsx#L42

**Comment by Majorfi** [comment]
This should be fixed with #58 as it was released in the last patch of the web lib
