### ISSUE TITLE
[Bug] Wrong address for Keeper, Strategist & Rewards

### ISSUE THREAD

**Issue by magikadev** [yearn/yearn-watch#63]
Strategies have wrong addresses.
[Example](https://yearn.watch/vault/0x8ee57c05741aA9DB947A744E713C15d4d19D8822/0x3cA0B4d7eedE71061B0bAdb4F0E86E99b0FEa613)

![image](https://user-images.githubusercontent.com/46446076/174206711-f186e1ac-0b37-47da-9b40-bfe5d8b67af1.png)

**Comment by Majorfi** [comment]
Fixed with #86
